name: Build phanpy-docker image

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' 

env:
  EXTERNAL_REPO: 'cheeaun/phanpy' 
  IMAGE_NAME: 'phanpy-docker'
  REGISTRY: 'ghcr.io'

jobs:
  build_and_push_image:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get latest phanpy release
        run: |
          curl -L -o release.tar.gz $(curl -s https://api.github.com/repos/cheeaun/phanpy/releases/latest | grep "browser_download_url" | grep ".tar.gz" | cut -d '"' -f 4)
      - name: Get phanpy release name
        run: |
          export RELEASE_NAME=$(curl -s https://api.github.com/repos/cheeaun/phanpy/releases/latest | grep '"tag_name"' | cut -d '"' -f 4)
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: | 
            ${{ github.actor }}/${{ env.IMAGE_NAME }}:latest
            ${{ github.actor }}/${{ env.IMAGE_NAME }}:${{ env.RELEASE_NAME }}

